version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/modoki-paas/modoki
    environment:
      GO111MODULE: on
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.05.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build
          command: go build
      - run:
          name: Build Docker image
          command: docker build -f ./Dockerfile-circleci -t modokipaas/modoki:$CIRCLE_BRANCH .
      - deploy:
          name: Push application Docker image
          command: |
            TAG=$CIRCLE_BRANCH
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push modokipaas/modoki:$TAG
