// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Modoki API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/modoki-paas/modoki/design
// --out=$(GOPATH)/src/github.com/modoki-paas/modoki
// --version=v1.4.0

package app
