// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Modoki API": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/modoki-paas/modoki/design
// --out=$(GOPATH)/src/github.com/modoki-paas/modoki
// --version=v1.3.1

package test
